name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ github.event.inputs.tag }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            dist/lspmultitool.user.js
