name: Build

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
      - name: Build
        run: npm run build
      - name: Publish Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
          files: |
            dist/lspmultitool.user.js
